					pix = nint(point(1:2))+1 - pbox(:,1)
					pix(1) = min(psize(1),max(1,pix(1)))
					pix(2) = min(psize(2),max(1,pix(2)))
					phase(1) = det_comps(1,di)
					phase(2) = point(3)*det_comps(2,di) - point(4)*det_comps(3,di)
					phase(3) = point(4)*det_comps(2,di) + point(3)*det_comps(3,di)
