export LAPACK_LINK = -L$(MKLPATH) -lmkl_rt -lpthread -lm
export OMP_LINK    = -liomp5
export FFLAGS      = -openmp -Ofast -fPIC -xhost -DUSE_MPI # -vec-report -opt-report
export FSAFE       = -openmp -O3 -fPIC -xhost -DUSE_MPI
export FC          = mpif90
export F2PY        = f2py
export F2PYCOMP    = intelem
export PYTHON      = python
export SED         = sed
export CC          = mpiCC
