export LAPACK_LINK = -L$(MKLROOT)/lib/intel64 -lmkl_intel_lp64 -lmkl_avx -lmkl_def -lmkl_core -lmkl_intel_thread -lpthread -lm
export OMP_LINK    = -liomp5
export FFLAGS      = -openmp -Ofast -fPIC
#export FFLAGS    = -O0 -g -debug all -check bounds -fPIC
export FSAFE       = -openmp -O3 -fPIC
export FC          = ifort
export F2PY        = f2py
export F2PYCOMP    = intelem
export PYTHON      = python
export SED         = sed
export CC          = icc
