export LAPACK_LINK = -llapack
export OMP_LINK    = -lgomp
export FFLAGS      = -fopenmp -Ofast -fPIC -ffree-line-length-none
export FSAFE       = -fopenmp -O3 -fPIC -ffree-line-length-none
export FC          = gfortran
export F2PY        = f2py2
export F2PYCOMP    = gfortran
export PYTHON      = python
export SED         = sed
export CC          = gcc
