export LAPACK_LINK = -llapack -lopenblas
export OMP_LINK    = -lgomp
export FFLAGS      = -fopenmp -O3 -ffast-math -fPIC -ffree-line-length-none -Wno-tabs
export FSAFE       = -fopenmp -O3 -fPIC -ffree-line-length-none -Wno-tabs
export FC          = gfortran
export F2PY        = f2py
export F2PYCOMP    = gfortran
export PYTHON      = python
export SED         = sed
export CC          = gcc
